name: Cypress

on: push

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      integration-tests: ${{ steps.parse.outputs.integration-tests }}
      # component-tests: ${{ steps.parse.outputs.component-tests }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        uses: cypress-io/github-action@v4
        with:
          runTests: false
          # build: npm run build
          
      # - name: Save build folder
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: build
      #     if-no-files-found: error
      #     path: build
      #     retention-days: 1

      - name: Parse test files for parallelization
        id: parse
        uses: tgamauf/cypress-parallel@v1
        with:
          count-runners: 2
  test:
    name: Cypress tests
    runs-on: ubuntu-latest
    needs: prepare
    strategy:
      fail-fast: false
      matrix:
        # Run the tests in parallel, each with one of the prepared test specs
        spec: ${{ fromJson(needs.prepare.outputs.integration-tests) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Execute tests
        uses: cypress-io/github-action@v4
        with:
          # We have already installed all dependencies above
          install: true
          # Use the spec provided to this worker to execute the test 
          spec: ${{ matrix.spec }}

